apiVersion: apps/v1
kind: Deployment
metadata:
  name: avaail-deployment
spec:
  selector:
    matchLabels:
      app: avaail-api
  replicas: 1
  template:
    metadata:
      labels:
        app: avaail-api
    spec:
      containers:
      - name: avaail-api
        image: avaail-api
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: avaail-api-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: avaail-api
